org: dandart
app: haskell-demo
service: slsdemo

environment:
  LANG: en_GB.UTF-8
  LC_ALL: en_GB.UTF-8

provider:
  name: aws
  region: eu-west-1
  runtime: haskell

functions:
  slsdemo:
    handler: slsdemo.slsdemo
    events:
      - http:
          path: /slsdemo
          method: post
          cors: true
          private: false
  github-pr:
    handler: slsdemo.githubpr
    events:
      - http:
          path: /github
          method: post
          cors: true
          private: false

plugins:
  - serverless-haskell