name:                sls
version:             0.1.0
github:              "danwdart/sls"
license:             BSD3
author:              "Dan Dart"
maintainer:          "stack@dandart.co.uk"
copyright:           "2019 Dan Dart"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/danwdart/sls#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- fakedata
- serverless-haskell
- text

library:
  source-dirs: src

executables:
  sls:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sls

tests:
  sls-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sls
