org: dandart
app: haskell-demo
service: sls

environment:
  LANG: en_GB.UTF-8
  LC_ALL: en_GB.UTF-8

provider:
  name: aws
  region: eu-west-1
  runtime: haskell

functions:
  sls-func:
    handler: sls.sls
    events:
      - http:
          path: /sls
          method: post
          cors: true
          private: false
  github-pr:
    handler: sls.githubpr
    events:
      - http:
          path: /github
          method: post
          cors: true
          private: false

plugins:
  - serverless-haskell