resolver: lts-14.5
packages:
- .
extra-deps:
  - Cabal-2.4.1.0
  - ghcjs-dom-0.9.4.0
  - ghcjs-dom-jsaddle-0.9.4.0
  - jsaddle-0.9.6.0
  - jsaddle-dom-0.9.3.2
  - jsaddle-warp-0.9.6.0
  - reactive-banana-1.2.1.0
  - ref-tf-0.4.0.1@sha256:369e5c6237e4b6fe330fde021b94a9f98971690cbec5b910faa9af3cbcb15610,1133

system-ghc: true
ghc-options:
  web: -Wall -Werror