<<<<<<< Updated upstream
language: node_js
node_js:
  - "12.2"
before_script:
  - npm install
  - npm run build
script:
  - npm test
=======
language: node_js
node_js:
  - "9.4"
before_script:
  - npm install
  - npm run build
script:
  - npm test
>>>>>>> Stashed changes
