resolver: lts-14.10
packages:
- .
extra-deps:
- async-2.2.2
- discord-haskell-1.1.0
- emoji-0.1.0.2@sha256:d995572a5c7dcd28f98eb15c6e387a7b3bda1ac2477ab0d9dba8580d5d7b161f
- req-2.1.0
- unix-2.7.2.2
- vector-0.12.0.3
system-ghc: true
ghc-options:
  other: -Wall -Werror
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]