resolver: lts-14.10
packages:
- .
extra-deps:
- async-2.2.2
- req-2.1.0
- unix-2.7.2.2
- vector-0.12.0.3
system-ghc: true
ghc-options:
  other: -Wall -Werror
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]